CREATE TABLE users(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    name varchar(100) NOT NULL ,
    rank varchar(100) NOT NULL

);

CREATE TABLE cars(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    user_id int references users(id),
    colour varchar(100) NOT NULL ,
    brand varchar(100) NOT NULL ,
    license_plate varchar(100) NOT NULL
);
